# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addurl.ui'
#
# Created: Sat Dec 06 04:31:41 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_addurlDialog(object):
    def setupUi(self, addurlDialog):
        addurlDialog.setObjectName(_fromUtf8("addurlDialog"))
        addurlDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        addurlDialog.resize(782, 507)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(addurlDialog.sizePolicy().hasHeightForWidth())
        addurlDialog.setSizePolicy(sizePolicy)
        addurlDialog.setMinimumSize(QtCore.QSize(782, 507))
        addurlDialog.setMaximumSize(QtCore.QSize(782, 507))
        self.addurltabWidget = QtGui.QTabWidget(addurlDialog)
        self.addurltabWidget.setGeometry(QtCore.QRect(26, 19, 731, 261))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.addurltabWidget.setFont(font)
        self.addurltabWidget.setObjectName(_fromUtf8("addurltabWidget"))
        self.singlesitetab = QtGui.QWidget()
        self.singlesitetab.setObjectName(_fromUtf8("singlesitetab"))
        self.singleaddButton = QtGui.QPushButton(self.singlesitetab)
        self.singleaddButton.setGeometry(QtCore.QRect(610, 10, 75, 23))
        self.singleaddButton.setObjectName(_fromUtf8("singleaddButton"))
        self.singleaddlabel = QtGui.QLabel(self.singlesitetab)
        self.singleaddlabel.setGeometry(QtCore.QRect(30, 10, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.singleaddlabel.setFont(font)
        self.singleaddlabel.setObjectName(_fromUtf8("singleaddlabel"))
        self.singleaddplainTextEdit = QtGui.QPlainTextEdit(self.singlesitetab)
        self.singleaddplainTextEdit.setGeometry(QtCore.QRect(30, 40, 661, 181))
        self.singleaddplainTextEdit.setObjectName(_fromUtf8("singleaddplainTextEdit"))
        self.addurltabWidget.addTab(self.singlesitetab, _fromUtf8(""))
        self.batchinputtab = QtGui.QWidget()
        self.batchinputtab.setObjectName(_fromUtf8("batchinputtab"))
        self.siteformatlabel = QtGui.QLabel(self.batchinputtab)
        self.siteformatlabel.setGeometry(QtCore.QRect(20, 10, 61, 21))
        self.siteformatlabel.setObjectName(_fromUtf8("siteformatlabel"))
        self.siteformatlineEdit = QtGui.QLineEdit(self.batchinputtab)
        self.siteformatlineEdit.setGeometry(QtCore.QRect(90, 10, 571, 20))
        self.siteformatlineEdit.setObjectName(_fromUtf8("siteformatlineEdit"))
        self.batchinputButton = QtGui.QPushButton(self.batchinputtab)
        self.batchinputButton.setGeometry(QtCore.QRect(630, 130, 75, 23))
        self.batchinputButton.setObjectName(_fromUtf8("batchinputButton"))
        self.geometricradioButton = QtGui.QRadioButton(self.batchinputtab)
        self.geometricradioButton.setGeometry(QtCore.QRect(30, 70, 89, 21))
        self.geometricradioButton.setObjectName(_fromUtf8("geometricradioButton"))
        self.alphabeticallyradioButton = QtGui.QRadioButton(self.batchinputtab)
        self.alphabeticallyradioButton.setGeometry(QtCore.QRect(30, 100, 89, 21))
        self.alphabeticallyradioButton.setObjectName(_fromUtf8("alphabeticallyradioButton"))
        self.arithmeticradioButton = QtGui.QRadioButton(self.batchinputtab)
        self.arithmeticradioButton.setGeometry(QtCore.QRect(30, 40, 89, 21))
        self.arithmeticradioButton.setCheckable(True)
        self.arithmeticradioButton.setChecked(False)
        self.arithmeticradioButton.setObjectName(_fromUtf8("arithmeticradioButton"))
        self.arithmeticfirstitemlabel = QtGui.QLabel(self.batchinputtab)
        self.arithmeticfirstitemlabel.setGeometry(QtCore.QRect(120, 40, 31, 21))
        self.arithmeticfirstitemlabel.setObjectName(_fromUtf8("arithmeticfirstitemlabel"))
        self.geometricfirstitemlabel = QtGui.QLabel(self.batchinputtab)
        self.geometricfirstitemlabel.setGeometry(QtCore.QRect(120, 70, 31, 21))
        self.geometricfirstitemlabel.setObjectName(_fromUtf8("geometricfirstitemlabel"))
        self.alphabeticallyfromlabel = QtGui.QLabel(self.batchinputtab)
        self.alphabeticallyfromlabel.setGeometry(QtCore.QRect(120, 100, 31, 21))
        self.alphabeticallyfromlabel.setObjectName(_fromUtf8("alphabeticallyfromlabel"))
        self.arithmeticfirstitemlineEdit = QtGui.QLineEdit(self.batchinputtab)
        self.arithmeticfirstitemlineEdit.setGeometry(QtCore.QRect(160, 40, 81, 20))
        self.arithmeticfirstitemlineEdit.setObjectName(_fromUtf8("arithmeticfirstitemlineEdit"))
        self.geometricfirstitemlineEdit = QtGui.QLineEdit(self.batchinputtab)
        self.geometricfirstitemlineEdit.setGeometry(QtCore.QRect(160, 70, 81, 20))
        self.geometricfirstitemlineEdit.setObjectName(_fromUtf8("geometricfirstitemlineEdit"))
        self.alphameticallyfromlineEdit = QtGui.QLineEdit(self.batchinputtab)
        self.alphameticallyfromlineEdit.setGeometry(QtCore.QRect(160, 100, 81, 20))
        self.alphameticallyfromlineEdit.setObjectName(_fromUtf8("alphameticallyfromlineEdit"))
        self.arithmeticitemslabel = QtGui.QLabel(self.batchinputtab)
        self.arithmeticitemslabel.setGeometry(QtCore.QRect(260, 40, 41, 21))
        self.arithmeticitemslabel.setObjectName(_fromUtf8("arithmeticitemslabel"))
        self.geometricitemslabel = QtGui.QLabel(self.batchinputtab)
        self.geometricitemslabel.setGeometry(QtCore.QRect(260, 70, 41, 21))
        self.geometricitemslabel.setObjectName(_fromUtf8("geometricitemslabel"))
        self.alphameticallytolabel = QtGui.QLabel(self.batchinputtab)
        self.alphameticallytolabel.setGeometry(QtCore.QRect(260, 100, 41, 21))
        self.alphameticallytolabel.setObjectName(_fromUtf8("alphameticallytolabel"))
        self.arithmeticitemnumberlineEdit = QtGui.QLineEdit(self.batchinputtab)
        self.arithmeticitemnumberlineEdit.setGeometry(QtCore.QRect(300, 40, 81, 20))
        self.arithmeticitemnumberlineEdit.setObjectName(_fromUtf8("arithmeticitemnumberlineEdit"))
        self.geometricitemnumberlineEdit = QtGui.QLineEdit(self.batchinputtab)
        self.geometricitemnumberlineEdit.setGeometry(QtCore.QRect(300, 70, 81, 20))
        self.geometricitemnumberlineEdit.setObjectName(_fromUtf8("geometricitemnumberlineEdit"))
        self.alphameticallytolineEdit = QtGui.QLineEdit(self.batchinputtab)
        self.alphameticallytolineEdit.setGeometry(QtCore.QRect(300, 100, 81, 20))
        self.alphameticallytolineEdit.setObjectName(_fromUtf8("alphameticallytolineEdit"))
        self.tolerancelabel = QtGui.QLabel(self.batchinputtab)
        self.tolerancelabel.setGeometry(QtCore.QRect(410, 40, 41, 21))
        self.tolerancelabel.setObjectName(_fromUtf8("tolerancelabel"))
        self.ratiolabel = QtGui.QLabel(self.batchinputtab)
        self.ratiolabel.setGeometry(QtCore.QRect(410, 70, 41, 21))
        self.ratiolabel.setObjectName(_fromUtf8("ratiolabel"))
        self.casesensitivelabel = QtGui.QLabel(self.batchinputtab)
        self.casesensitivelabel.setGeometry(QtCore.QRect(410, 100, 91, 21))
        self.casesensitivelabel.setObjectName(_fromUtf8("casesensitivelabel"))
        self.tolerancelineEdit = QtGui.QLineEdit(self.batchinputtab)
        self.tolerancelineEdit.setGeometry(QtCore.QRect(450, 40, 113, 20))
        self.tolerancelineEdit.setObjectName(_fromUtf8("tolerancelineEdit"))
        self.ratiolineEdit = QtGui.QLineEdit(self.batchinputtab)
        self.ratiolineEdit.setGeometry(QtCore.QRect(450, 70, 113, 20))
        self.ratiolineEdit.setObjectName(_fromUtf8("ratiolineEdit"))
        self.batchinputpreviewtextBrowser = QtGui.QTextBrowser(self.batchinputtab)
        self.batchinputpreviewtextBrowser.setGeometry(QtCore.QRect(30, 160, 671, 71))
        self.batchinputpreviewtextBrowser.setObjectName(_fromUtf8("batchinputpreviewtextBrowser"))
        self.batchinputpreviewlabel = QtGui.QLabel(self.batchinputtab)
        self.batchinputpreviewlabel.setGeometry(QtCore.QRect(20, 135, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.batchinputpreviewlabel.setFont(font)
        self.batchinputpreviewlabel.setObjectName(_fromUtf8("batchinputpreviewlabel"))
        self.wildcardpushButton = QtGui.QPushButton(self.batchinputtab)
        self.wildcardpushButton.setGeometry(QtCore.QRect(670, 10, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.wildcardpushButton.setFont(font)
        self.wildcardpushButton.setObjectName(_fromUtf8("wildcardpushButton"))
        self.addurltabWidget.addTab(self.batchinputtab, _fromUtf8(""))
        self.textimporttab = QtGui.QWidget()
        self.textimporttab.setObjectName(_fromUtf8("textimporttab"))
        self.textimportlocationlabel = QtGui.QLabel(self.textimporttab)
        self.textimportlocationlabel.setGeometry(QtCore.QRect(30, 10, 61, 21))
        self.textimportlocationlabel.setObjectName(_fromUtf8("textimportlocationlabel"))
        self.textimportlocationlineEdit = QtGui.QLineEdit(self.textimporttab)
        self.textimportlocationlineEdit.setGeometry(QtCore.QRect(100, 10, 491, 20))
        self.textimportlocationlineEdit.setReadOnly(True)
        self.textimportlocationlineEdit.setObjectName(_fromUtf8("textimportlocationlineEdit"))
        self.textimportlocationpushButton = QtGui.QPushButton(self.textimporttab)
        self.textimportlocationpushButton.setGeometry(QtCore.QRect(610, 10, 75, 23))
        self.textimportlocationpushButton.setObjectName(_fromUtf8("textimportlocationpushButton"))
        self.textimportpreviewlabel = QtGui.QLabel(self.textimporttab)
        self.textimportpreviewlabel.setGeometry(QtCore.QRect(30, 50, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textimportpreviewlabel.setFont(font)
        self.textimportpreviewlabel.setObjectName(_fromUtf8("textimportpreviewlabel"))
        self.textimportButton = QtGui.QPushButton(self.textimporttab)
        self.textimportButton.setGeometry(QtCore.QRect(610, 45, 75, 23))
        self.textimportButton.setObjectName(_fromUtf8("textimportButton"))
        self.textimportpreviewtextBrowser = QtGui.QTextBrowser(self.textimporttab)
        self.textimportpreviewtextBrowser.setGeometry(QtCore.QRect(40, 75, 641, 141))
        self.textimportpreviewtextBrowser.setObjectName(_fromUtf8("textimportpreviewtextBrowser"))
        self.addurltabWidget.addTab(self.textimporttab, _fromUtf8(""))
        self.allurllabel = QtGui.QLabel(addurlDialog)
        self.allurllabel.setGeometry(QtCore.QRect(30, 290, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.allurllabel.setFont(font)
        self.allurllabel.setObjectName(_fromUtf8("allurllabel"))
        self.allurltextBrowser = QtGui.QTextBrowser(addurlDialog)
        self.allurltextBrowser.setGeometry(QtCore.QRect(30, 320, 721, 131))
        self.allurltextBrowser.setObjectName(_fromUtf8("allurltextBrowser"))
        self.okButton = QtGui.QPushButton(addurlDialog)
        self.okButton.setGeometry(QtCore.QRect(570, 470, 75, 23))
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.cancelButton = QtGui.QPushButton(addurlDialog)
        self.cancelButton.setGeometry(QtCore.QRect(670, 470, 75, 23))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))

        self.retranslateUi(addurlDialog)
        self.addurltabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(addurlDialog)

    def retranslateUi(self, addurlDialog):
        addurlDialog.setWindowTitle(_translate("addurlDialog", "添加起始URL", None))
        self.singleaddButton.setText(_translate("addurlDialog", "添加", None))
        self.singleaddlabel.setText(_translate("addurlDialog", "逐条输入网址：（一行一个）", None))
        self.singleaddplainTextEdit.setPlainText(_translate("addurlDialog", "http://", None))
        self.addurltabWidget.setTabText(self.addurltabWidget.indexOf(self.singlesitetab), _translate("addurlDialog", "单条网址", None))
        self.siteformatlabel.setText(_translate("addurlDialog", "地址格式：", None))
        self.siteformatlineEdit.setText(_translate("addurlDialog", "http://", None))
        self.batchinputButton.setText(_translate("addurlDialog", "添加", None))
        self.geometricradioButton.setText(_translate("addurlDialog", "等比数列", None))
        self.alphabeticallyradioButton.setText(_translate("addurlDialog", "字母变化", None))
        self.arithmeticradioButton.setText(_translate("addurlDialog", "等差数列", None))
        self.arithmeticfirstitemlabel.setText(_translate("addurlDialog", "首项", None))
        self.geometricfirstitemlabel.setText(_translate("addurlDialog", "首项", None))
        self.alphabeticallyfromlabel.setText(_translate("addurlDialog", "从", None))
        self.arithmeticfirstitemlineEdit.setText(_translate("addurlDialog", "0", None))
        self.geometricfirstitemlineEdit.setText(_translate("addurlDialog", "1", None))
        self.alphameticallyfromlineEdit.setText(_translate("addurlDialog", "a", None))
        self.arithmeticitemslabel.setText(_translate("addurlDialog", "项数", None))
        self.geometricitemslabel.setText(_translate("addurlDialog", "项数", None))
        self.alphameticallytolabel.setText(_translate("addurlDialog", "到", None))
        self.arithmeticitemnumberlineEdit.setText(_translate("addurlDialog", "5", None))
        self.geometricitemnumberlineEdit.setText(_translate("addurlDialog", "5", None))
        self.alphameticallytolineEdit.setText(_translate("addurlDialog", "z", None))
        self.tolerancelabel.setText(_translate("addurlDialog", "公差", None))
        self.ratiolabel.setText(_translate("addurlDialog", "公比", None))
        self.casesensitivelabel.setText(_translate("addurlDialog", "（区分大小写）", None))
        self.tolerancelineEdit.setText(_translate("addurlDialog", "1", None))
        self.ratiolineEdit.setText(_translate("addurlDialog", "2", None))
        self.batchinputpreviewlabel.setText(_translate("addurlDialog", "预览：", None))
        self.wildcardpushButton.setText(_translate("addurlDialog", "(*)", None))
        self.addurltabWidget.setTabText(self.addurltabWidget.indexOf(self.batchinputtab), _translate("addurlDialog", "批量输入", None))
        self.textimportlocationlabel.setText(_translate("addurlDialog", "文本位置：", None))
        self.textimportlocationpushButton.setText(_translate("addurlDialog", "浏览", None))
        self.textimportpreviewlabel.setText(_translate("addurlDialog", "预览：", None))
        self.textimportButton.setText(_translate("addurlDialog", "添加", None))
        self.addurltabWidget.setTabText(self.addurltabWidget.indexOf(self.textimporttab), _translate("addurlDialog", "文本导入", None))
        self.allurllabel.setText(_translate("addurlDialog", "全部URL：", None))
        self.okButton.setText(_translate("addurlDialog", "确定", None))
        self.cancelButton.setText(_translate("addurlDialog", "取消", None))

