# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sat Dec 06 20:18:40 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(985, 652)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.centralLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.centralLayout.setSpacing(20)
        self.centralLayout.setContentsMargins(20, -1, 20, -1)
        self.centralLayout.setObjectName(_fromUtf8("centralLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.settingtab = QtGui.QWidget()
        self.settingtab.setObjectName(_fromUtf8("settingtab"))
        self.settingLayout = QtGui.QVBoxLayout(self.settingtab)
        self.settingLayout.setSpacing(15)
        self.settingLayout.setContentsMargins(18, 13, 18, 21)
        self.settingLayout.setObjectName(_fromUtf8("settingLayout"))
        self.urlgroupBox = QtGui.QGroupBox(self.settingtab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.urlgroupBox.setFont(font)
        self.urlgroupBox.setObjectName(_fromUtf8("urlgroupBox"))
        self.urlgroupLayout = QtGui.QHBoxLayout(self.urlgroupBox)
        self.urlgroupLayout.setSpacing(16)
        self.urlgroupLayout.setContentsMargins(20, -1, 8, -1)
        self.urlgroupLayout.setObjectName(_fromUtf8("urlgroupLayout"))
        self.urltextBrowser = QtGui.QTextBrowser(self.urlgroupBox)
        self.urltextBrowser.setObjectName(_fromUtf8("urltextBrowser"))
        self.urlgroupLayout.addWidget(self.urltextBrowser)
        self.urlbuttonLayout = QtGui.QVBoxLayout()
        self.urlbuttonLayout.setSpacing(6)
        self.urlbuttonLayout.setObjectName(_fromUtf8("urlbuttonLayout"))
        self.addurlButton = QtGui.QPushButton(self.urlgroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addurlButton.sizePolicy().hasHeightForWidth())
        self.addurlButton.setSizePolicy(sizePolicy)
        self.addurlButton.setMaximumSize(QtCore.QSize(71, 21))
        self.addurlButton.setObjectName(_fromUtf8("addurlButton"))
        self.urlbuttonLayout.addWidget(self.addurlButton)
        self.modifyurlButton = QtGui.QPushButton(self.urlgroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modifyurlButton.sizePolicy().hasHeightForWidth())
        self.modifyurlButton.setSizePolicy(sizePolicy)
        self.modifyurlButton.setMaximumSize(QtCore.QSize(71, 21))
        self.modifyurlButton.setObjectName(_fromUtf8("modifyurlButton"))
        self.urlbuttonLayout.addWidget(self.modifyurlButton)
        self.deleteurlButton = QtGui.QPushButton(self.urlgroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteurlButton.sizePolicy().hasHeightForWidth())
        self.deleteurlButton.setSizePolicy(sizePolicy)
        self.deleteurlButton.setMaximumSize(QtCore.QSize(71, 21))
        self.deleteurlButton.setObjectName(_fromUtf8("deleteurlButton"))
        self.urlbuttonLayout.addWidget(self.deleteurlButton)
        self.emptyurlButton = QtGui.QPushButton(self.urlgroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emptyurlButton.sizePolicy().hasHeightForWidth())
        self.emptyurlButton.setSizePolicy(sizePolicy)
        self.emptyurlButton.setMaximumSize(QtCore.QSize(71, 21))
        self.emptyurlButton.setObjectName(_fromUtf8("emptyurlButton"))
        self.urlbuttonLayout.addWidget(self.emptyurlButton)
        self.urlgroupLayout.addLayout(self.urlbuttonLayout)
        self.urlgroupLayout.setStretch(0, 98)
        self.urlgroupLayout.setStretch(1, 11)
        self.settingLayout.addWidget(self.urlgroupBox)
        self.rulegroupBox = QtGui.QGroupBox(self.settingtab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rulegroupBox.setFont(font)
        self.rulegroupBox.setObjectName(_fromUtf8("rulegroupBox"))
        self.rulegroupLayout = QtGui.QHBoxLayout(self.rulegroupBox)
        self.rulegroupLayout.setSpacing(18)
        self.rulegroupLayout.setContentsMargins(20, -1, 12, -1)
        self.rulegroupLayout.setObjectName(_fromUtf8("rulegroupLayout"))
        self.ruleLayout = QtGui.QVBoxLayout()
        self.ruleLayout.setSpacing(8)
        self.ruleLayout.setObjectName(_fromUtf8("ruleLayout"))
        self.autoacquireradioButton = QtGui.QRadioButton(self.rulegroupBox)
        self.autoacquireradioButton.setObjectName(_fromUtf8("autoacquireradioButton"))
        self.ruleLayout.addWidget(self.autoacquireradioButton)
        self.matchradioButton = QtGui.QRadioButton(self.rulegroupBox)
        self.matchradioButton.setObjectName(_fromUtf8("matchradioButton"))
        self.ruleLayout.addWidget(self.matchradioButton)
        self.xpathradioButton = QtGui.QRadioButton(self.rulegroupBox)
        self.xpathradioButton.setObjectName(_fromUtf8("xpathradioButton"))
        self.ruleLayout.addWidget(self.xpathradioButton)
        self.rulegroupLayout.addLayout(self.ruleLayout)
        self.ruleplainTextEdit = QtGui.QPlainTextEdit(self.rulegroupBox)
        self.ruleplainTextEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.ruleplainTextEdit.setObjectName(_fromUtf8("ruleplainTextEdit"))
        self.rulegroupLayout.addWidget(self.ruleplainTextEdit)
        self.ruletextlabel = QtGui.QLabel(self.rulegroupBox)
        self.ruletextlabel.setObjectName(_fromUtf8("ruletextlabel"))
        self.rulegroupLayout.addWidget(self.ruletextlabel)
        self.rulegroupLayout.setStretch(0, 25)
        self.rulegroupLayout.setStretch(1, 130)
        self.rulegroupLayout.setStretch(2, 10)
        self.settingLayout.addWidget(self.rulegroupBox)
        self.argumentandsaveLayout = QtGui.QHBoxLayout()
        self.argumentandsaveLayout.setSpacing(28)
        self.argumentandsaveLayout.setObjectName(_fromUtf8("argumentandsaveLayout"))
        self.argumentgroupBox = QtGui.QGroupBox(self.settingtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.argumentgroupBox.sizePolicy().hasHeightForWidth())
        self.argumentgroupBox.setSizePolicy(sizePolicy)
        self.argumentgroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.argumentgroupBox.setFont(font)
        self.argumentgroupBox.setObjectName(_fromUtf8("argumentgroupBox"))
        self.argumentgroupLayout = QtGui.QGridLayout(self.argumentgroupBox)
        self.argumentgroupLayout.setContentsMargins(20, -1, -1, -1)
        self.argumentgroupLayout.setObjectName(_fromUtf8("argumentgroupLayout"))
        self.resolvethreadLabel = QtGui.QLabel(self.argumentgroupBox)
        self.resolvethreadLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.resolvethreadLabel.setObjectName(_fromUtf8("resolvethreadLabel"))
        self.argumentgroupLayout.addWidget(self.resolvethreadLabel, 9, 0, 1, 1)
        self.crawlthreadLabel = QtGui.QLabel(self.argumentgroupBox)
        self.crawlthreadLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.crawlthreadLabel.setObjectName(_fromUtf8("crawlthreadLabel"))
        self.argumentgroupLayout.addWidget(self.crawlthreadLabel, 8, 0, 1, 1)
        self.analysethreadspinBox = QtGui.QSpinBox(self.argumentgroupBox)
        self.analysethreadspinBox.setEnabled(True)
        self.analysethreadspinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.analysethreadspinBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.analysethreadspinBox.setMinimum(1)
        self.analysethreadspinBox.setProperty("value", 3)
        self.analysethreadspinBox.setObjectName(_fromUtf8("analysethreadspinBox"))
        self.argumentgroupLayout.addWidget(self.analysethreadspinBox, 9, 1, 1, 1)
        self.crawlthreadspinBox = QtGui.QSpinBox(self.argumentgroupBox)
        self.crawlthreadspinBox.setEnabled(True)
        self.crawlthreadspinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.crawlthreadspinBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.crawlthreadspinBox.setMinimum(1)
        self.crawlthreadspinBox.setProperty("value", 3)
        self.crawlthreadspinBox.setObjectName(_fromUtf8("crawlthreadspinBox"))
        self.argumentgroupLayout.addWidget(self.crawlthreadspinBox, 8, 1, 1, 1)
        self.requesttimeLabel = QtGui.QLabel(self.argumentgroupBox)
        self.requesttimeLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.requesttimeLabel.setObjectName(_fromUtf8("requesttimeLabel"))
        self.argumentgroupLayout.addWidget(self.requesttimeLabel, 7, 0, 1, 1)
        self.depthLabel = QtGui.QLabel(self.argumentgroupBox)
        self.depthLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.depthLabel.setObjectName(_fromUtf8("depthLabel"))
        self.argumentgroupLayout.addWidget(self.depthLabel, 5, 0, 1, 1)
        self.pagenumberLabel = QtGui.QLabel(self.argumentgroupBox)
        self.pagenumberLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.pagenumberLabel.setObjectName(_fromUtf8("pagenumberLabel"))
        self.argumentgroupLayout.addWidget(self.pagenumberLabel, 3, 0, 1, 1)
        self.millisecondLabel = QtGui.QLabel(self.argumentgroupBox)
        self.millisecondLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.millisecondLabel.setObjectName(_fromUtf8("millisecondLabel"))
        self.argumentgroupLayout.addWidget(self.millisecondLabel, 7, 2, 1, 1)
        self.depthexplainlabel = QtGui.QLabel(self.argumentgroupBox)
        self.depthexplainlabel.setObjectName(_fromUtf8("depthexplainlabel"))
        self.argumentgroupLayout.addWidget(self.depthexplainlabel, 5, 2, 1, 1)
        self.depthspinBox = QtGui.QSpinBox(self.argumentgroupBox)
        self.depthspinBox.setEnabled(True)
        self.depthspinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.depthspinBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.depthspinBox.setProperty("value", 3)
        self.depthspinBox.setObjectName(_fromUtf8("depthspinBox"))
        self.argumentgroupLayout.addWidget(self.depthspinBox, 5, 1, 1, 1)
        self.pagenumberspinBox = QtGui.QSpinBox(self.argumentgroupBox)
        self.pagenumberspinBox.setEnabled(True)
        self.pagenumberspinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.pagenumberspinBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pagenumberspinBox.setMaximum(5000)
        self.pagenumberspinBox.setProperty("value", 1000)
        self.pagenumberspinBox.setObjectName(_fromUtf8("pagenumberspinBox"))
        self.argumentgroupLayout.addWidget(self.pagenumberspinBox, 3, 1, 1, 1)
        self.pagenumberexplainlabel = QtGui.QLabel(self.argumentgroupBox)
        self.pagenumberexplainlabel.setObjectName(_fromUtf8("pagenumberexplainlabel"))
        self.argumentgroupLayout.addWidget(self.pagenumberexplainlabel, 3, 2, 1, 1)
        self.requesttimespinBox = QtGui.QSpinBox(self.argumentgroupBox)
        self.requesttimespinBox.setEnabled(True)
        self.requesttimespinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.requesttimespinBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.requesttimespinBox.setMinimum(10)
        self.requesttimespinBox.setMaximum(3000)
        self.requesttimespinBox.setProperty("value", 300)
        self.requesttimespinBox.setObjectName(_fromUtf8("requesttimespinBox"))
        self.argumentgroupLayout.addWidget(self.requesttimespinBox, 7, 1, 1, 1)
        self.argumentandsaveLayout.addWidget(self.argumentgroupBox)
        self.savegroupBox = QtGui.QGroupBox(self.settingtab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.savegroupBox.setFont(font)
        self.savegroupBox.setObjectName(_fromUtf8("savegroupBox"))
        self.savegroupLayout = QtGui.QGridLayout(self.savegroupBox)
        self.savegroupLayout.setContentsMargins(20, -1, -1, -1)
        self.savegroupLayout.setObjectName(_fromUtf8("savegroupLayout"))
        self.codingcomboBox = QtGui.QComboBox(self.savegroupBox)
        self.codingcomboBox.setMaximumSize(QtCore.QSize(151, 16777215))
        self.codingcomboBox.setObjectName(_fromUtf8("codingcomboBox"))
        self.codingcomboBox.addItem(_fromUtf8(""))
        self.codingcomboBox.addItem(_fromUtf8(""))
        self.savegroupLayout.addWidget(self.codingcomboBox, 9, 1, 1, 1)
        self.savelocationLabel = QtGui.QLabel(self.savegroupBox)
        self.savelocationLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.savelocationLabel.setObjectName(_fromUtf8("savelocationLabel"))
        self.savegroupLayout.addWidget(self.savelocationLabel, 3, 0, 1, 1)
        self.namingLabel = QtGui.QLabel(self.savegroupBox)
        self.namingLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.namingLabel.setObjectName(_fromUtf8("namingLabel"))
        self.savegroupLayout.addWidget(self.namingLabel, 6, 0, 1, 1)
        self.saveformatLabel = QtGui.QLabel(self.savegroupBox)
        self.saveformatLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.saveformatLabel.setObjectName(_fromUtf8("saveformatLabel"))
        self.savegroupLayout.addWidget(self.saveformatLabel, 5, 0, 1, 1)
        self.downloadnumberspinBox = QtGui.QSpinBox(self.savegroupBox)
        self.downloadnumberspinBox.setEnabled(True)
        self.downloadnumberspinBox.setMaximumSize(QtCore.QSize(81, 16777215))
        self.downloadnumberspinBox.setMinimum(1)
        self.downloadnumberspinBox.setProperty("value", 3)
        self.downloadnumberspinBox.setObjectName(_fromUtf8("downloadnumberspinBox"))
        self.savegroupLayout.addWidget(self.downloadnumberspinBox, 10, 1, 1, 1)
        self.downloadnumberLabel = QtGui.QLabel(self.savegroupBox)
        self.downloadnumberLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.downloadnumberLabel.setObjectName(_fromUtf8("downloadnumberLabel"))
        self.savegroupLayout.addWidget(self.downloadnumberLabel, 10, 0, 1, 1)
        self.namingcomboBox = QtGui.QComboBox(self.savegroupBox)
        self.namingcomboBox.setMaximumSize(QtCore.QSize(151, 16777215))
        self.namingcomboBox.setObjectName(_fromUtf8("namingcomboBox"))
        self.namingcomboBox.addItem(_fromUtf8(""))
        self.namingcomboBox.addItem(_fromUtf8(""))
        self.namingcomboBox.addItem(_fromUtf8(""))
        self.namingcomboBox.addItem(_fromUtf8(""))
        self.savegroupLayout.addWidget(self.namingcomboBox, 6, 1, 1, 1)
        self.codingLabel = QtGui.QLabel(self.savegroupBox)
        self.codingLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.codingLabel.setObjectName(_fromUtf8("codingLabel"))
        self.savegroupLayout.addWidget(self.codingLabel, 9, 0, 1, 1)
        self.savelocationpushButton = QtGui.QPushButton(self.savegroupBox)
        self.savelocationpushButton.setMinimumSize(QtCore.QSize(28, 20))
        self.savelocationpushButton.setMaximumSize(QtCore.QSize(28, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.savelocationpushButton.setFont(font)
        self.savelocationpushButton.setObjectName(_fromUtf8("savelocationpushButton"))
        self.savegroupLayout.addWidget(self.savelocationpushButton, 3, 2, 1, 1)
        self.saveformatcomboBox = QtGui.QComboBox(self.savegroupBox)
        self.saveformatcomboBox.setMaximumSize(QtCore.QSize(151, 16777215))
        self.saveformatcomboBox.setObjectName(_fromUtf8("saveformatcomboBox"))
        self.saveformatcomboBox.addItem(_fromUtf8(""))
        self.saveformatcomboBox.addItem(_fromUtf8(""))
        self.savegroupLayout.addWidget(self.saveformatcomboBox, 5, 1, 1, 1)
        self.savelocationlineEdit = QtGui.QLineEdit(self.savegroupBox)
        self.savelocationlineEdit.setMinimumSize(QtCore.QSize(319, 0))
        self.savelocationlineEdit.setMaximumSize(QtCore.QSize(400, 16777215))
        self.savelocationlineEdit.setReadOnly(True)
        self.savelocationlineEdit.setObjectName(_fromUtf8("savelocationlineEdit"))
        self.savegroupLayout.addWidget(self.savelocationlineEdit, 3, 1, 1, 1)
        self.savelocationspaceLabel = QtGui.QLabel(self.savegroupBox)
        self.savelocationspaceLabel.setText(_fromUtf8(""))
        self.savelocationspaceLabel.setObjectName(_fromUtf8("savelocationspaceLabel"))
        self.savegroupLayout.addWidget(self.savelocationspaceLabel, 3, 3, 1, 1)
        self.argumentandsaveLayout.addWidget(self.savegroupBox)
        self.argumentandsaveLayout.setStretch(0, 30)
        self.argumentandsaveLayout.setStretch(1, 50)
        self.settingLayout.addLayout(self.argumentandsaveLayout)
        self.settingLayout.setStretch(0, 40)
        self.settingLayout.setStretch(1, 30)
        self.settingLayout.setStretch(2, 45)
        self.tabWidget.addTab(self.settingtab, _fromUtf8(""))
        self.displaytab = QtGui.QWidget()
        self.displaytab.setObjectName(_fromUtf8("displaytab"))
        self.displayLayout = QtGui.QVBoxLayout(self.displaytab)
        self.displayLayout.setSpacing(15)
        self.displayLayout.setContentsMargins(18, 13, 18, 21)
        self.displayLayout.setObjectName(_fromUtf8("displayLayout"))
        self.resultgroupBox = QtGui.QGroupBox(self.displaytab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resultgroupBox.setFont(font)
        self.resultgroupBox.setObjectName(_fromUtf8("resultgroupBox"))
        self.resultgroupLayout = QtGui.QVBoxLayout(self.resultgroupBox)
        self.resultgroupLayout.setContentsMargins(20, -1, 20, 15)
        self.resultgroupLayout.setObjectName(_fromUtf8("resultgroupLayout"))
        self.resulttableWidget = QtGui.QTableWidget(self.resultgroupBox)
        self.resulttableWidget.setLineWidth(1)
        self.resulttableWidget.setMidLineWidth(0)
        self.resulttableWidget.setObjectName(_fromUtf8("resulttableWidget"))
        self.resulttableWidget.setColumnCount(6)
        self.resulttableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.resulttableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.resulttableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.resulttableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.resulttableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.resulttableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.resulttableWidget.setHorizontalHeaderItem(5, item)
        self.resultgroupLayout.addWidget(self.resulttableWidget)
        self.displayLayout.addWidget(self.resultgroupBox)
        self.conditiongroupBox = QtGui.QGroupBox(self.displaytab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.conditiongroupBox.setFont(font)
        self.conditiongroupBox.setObjectName(_fromUtf8("conditiongroupBox"))
        self.conditiongroupLayout = QtGui.QVBoxLayout(self.conditiongroupBox)
        self.conditiongroupLayout.setContentsMargins(30, 8, 9, 15)
        self.conditiongroupLayout.setObjectName(_fromUtf8("conditiongroupLayout"))
        self.conditiongridLayout = QtGui.QGridLayout()
        self.conditiongridLayout.setObjectName(_fromUtf8("conditiongridLayout"))
        self.statusLabel = QtGui.QLabel(self.conditiongroupBox)
        self.statusLabel.setMaximumSize(QtCore.QSize(118, 16777215))
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.conditiongridLayout.addWidget(self.statusLabel, 0, 0, 1, 1)
        self.statusdisplayLabel = QtGui.QLabel(self.conditiongroupBox)
        self.statusdisplayLabel.setObjectName(_fromUtf8("statusdisplayLabel"))
        self.conditiongridLayout.addWidget(self.statusdisplayLabel, 0, 1, 1, 1)
        self.succeedednumberLabel = QtGui.QLabel(self.conditiongroupBox)
        self.succeedednumberLabel.setMaximumSize(QtCore.QSize(129, 16777215))
        self.succeedednumberLabel.setObjectName(_fromUtf8("succeedednumberLabel"))
        self.conditiongridLayout.addWidget(self.succeedednumberLabel, 0, 2, 1, 1)
        self.succeedednumberdisplayLabel = QtGui.QLabel(self.conditiongroupBox)
        self.succeedednumberdisplayLabel.setObjectName(_fromUtf8("succeedednumberdisplayLabel"))
        self.conditiongridLayout.addWidget(self.succeedednumberdisplayLabel, 0, 3, 1, 1)
        self.downloadsizeLabel = QtGui.QLabel(self.conditiongroupBox)
        self.downloadsizeLabel.setMaximumSize(QtCore.QSize(133, 16777215))
        self.downloadsizeLabel.setObjectName(_fromUtf8("downloadsizeLabel"))
        self.conditiongridLayout.addWidget(self.downloadsizeLabel, 0, 4, 1, 1)
        self.downloadsizedisplayLabel = QtGui.QLabel(self.conditiongroupBox)
        self.downloadsizedisplayLabel.setObjectName(_fromUtf8("downloadsizedisplayLabel"))
        self.conditiongridLayout.addWidget(self.downloadsizedisplayLabel, 0, 5, 1, 1)
        self.runtimeLabel = QtGui.QLabel(self.conditiongroupBox)
        self.runtimeLabel.setMaximumSize(QtCore.QSize(118, 16777215))
        self.runtimeLabel.setObjectName(_fromUtf8("runtimeLabel"))
        self.conditiongridLayout.addWidget(self.runtimeLabel, 1, 0, 1, 1)
        self.runtimedisplayLabel = QtGui.QLabel(self.conditiongroupBox)
        self.runtimedisplayLabel.setObjectName(_fromUtf8("runtimedisplayLabel"))
        self.conditiongridLayout.addWidget(self.runtimedisplayLabel, 1, 1, 1, 1)
        self.failednumberLabel_ = QtGui.QLabel(self.conditiongroupBox)
        self.failednumberLabel_.setMaximumSize(QtCore.QSize(129, 16777215))
        self.failednumberLabel_.setObjectName(_fromUtf8("failednumberLabel_"))
        self.conditiongridLayout.addWidget(self.failednumberLabel_, 1, 2, 1, 1)
        self.failednumberdisplayLabel = QtGui.QLabel(self.conditiongroupBox)
        self.failednumberdisplayLabel.setObjectName(_fromUtf8("failednumberdisplayLabel"))
        self.conditiongridLayout.addWidget(self.failednumberdisplayLabel, 1, 3, 1, 1)
        self.downloadspeedLabel = QtGui.QLabel(self.conditiongroupBox)
        self.downloadspeedLabel.setMaximumSize(QtCore.QSize(133, 16777215))
        self.downloadspeedLabel.setObjectName(_fromUtf8("downloadspeedLabel"))
        self.conditiongridLayout.addWidget(self.downloadspeedLabel, 1, 4, 1, 1)
        self.downloadspeeddisplayLabel = QtGui.QLabel(self.conditiongroupBox)
        self.downloadspeeddisplayLabel.setObjectName(_fromUtf8("downloadspeeddisplayLabel"))
        self.conditiongridLayout.addWidget(self.downloadspeeddisplayLabel, 1, 5, 1, 1)
        self.crawlednumberLabel = QtGui.QLabel(self.conditiongroupBox)
        self.crawlednumberLabel.setMaximumSize(QtCore.QSize(118, 16777215))
        self.crawlednumberLabel.setObjectName(_fromUtf8("crawlednumberLabel"))
        self.conditiongridLayout.addWidget(self.crawlednumberLabel, 2, 0, 1, 1)
        self.crawlednumberdisplayLabel = QtGui.QLabel(self.conditiongroupBox)
        self.crawlednumberdisplayLabel.setObjectName(_fromUtf8("crawlednumberdisplayLabel"))
        self.conditiongridLayout.addWidget(self.crawlednumberdisplayLabel, 2, 1, 1, 1)
        self.errornumberLabel = QtGui.QLabel(self.conditiongroupBox)
        self.errornumberLabel.setMaximumSize(QtCore.QSize(129, 16777215))
        self.errornumberLabel.setObjectName(_fromUtf8("errornumberLabel"))
        self.conditiongridLayout.addWidget(self.errornumberLabel, 2, 2, 1, 1)
        self.errornumberdisplayLabel = QtGui.QLabel(self.conditiongroupBox)
        self.errornumberdisplayLabel.setObjectName(_fromUtf8("errornumberdisplayLabel"))
        self.conditiongridLayout.addWidget(self.errornumberdisplayLabel, 2, 3, 1, 1)
        self.conditiongroupLayout.addLayout(self.conditiongridLayout)
        self.displayLayout.addWidget(self.conditiongroupBox)
        self.displayLayout.setStretch(0, 13)
        self.displayLayout.setStretch(1, 6)
        self.tabWidget.addTab(self.displaytab, _fromUtf8(""))
        self.centralLayout.addWidget(self.tabWidget)
        self.nameandcontrolhorizontalLayout = QtGui.QHBoxLayout()
        self.nameandcontrolhorizontalLayout.setSpacing(0)
        self.nameandcontrolhorizontalLayout.setContentsMargins(20, -1, 10, -1)
        self.nameandcontrolhorizontalLayout.setObjectName(_fromUtf8("nameandcontrolhorizontalLayout"))
        self.nameLayout = QtGui.QHBoxLayout()
        self.nameLayout.setSpacing(0)
        self.nameLayout.setContentsMargins(-1, 0, -1, -1)
        self.nameLayout.setObjectName(_fromUtf8("nameLayout"))
        self.nametitleLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nametitleLabel.setFont(font)
        self.nametitleLabel.setObjectName(_fromUtf8("nametitleLabel"))
        self.nameLayout.addWidget(self.nametitleLabel)
        self.projectnameLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.projectnameLabel.setFont(font)
        self.projectnameLabel.setObjectName(_fromUtf8("projectnameLabel"))
        self.nameLayout.addWidget(self.projectnameLabel)
        self.nameandcontrolhorizontalLayout.addLayout(self.nameLayout)
        self.controlLayout = QtGui.QHBoxLayout()
        self.controlLayout.setSpacing(20)
        self.controlLayout.setObjectName(_fromUtf8("controlLayout"))
        spacerItem = QtGui.QSpacerItem(602, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.controlLayout.addItem(spacerItem)
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setIconSize(QtCore.QSize(16, 16))
        self.startButton.setAutoRepeatDelay(300)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.controlLayout.addWidget(self.startButton)
        self.pauseButton = QtGui.QPushButton(self.centralwidget)
        self.pauseButton.setObjectName(_fromUtf8("pauseButton"))
        self.controlLayout.addWidget(self.pauseButton)
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.controlLayout.addWidget(self.stopButton)
        self.nameandcontrolhorizontalLayout.addLayout(self.controlLayout)
        self.centralLayout.addLayout(self.nameandcontrolhorizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 985, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.filemenu = QtGui.QMenu(self.menubar)
        self.filemenu.setObjectName(_fromUtf8("filemenu"))
        self.optionmenu = QtGui.QMenu(self.menubar)
        self.optionmenu.setObjectName(_fromUtf8("optionmenu"))
        self.helpmenu = QtGui.QMenu(self.menubar)
        self.helpmenu.setObjectName(_fromUtf8("helpmenu"))
        self.analysemenu = QtGui.QMenu(self.menubar)
        self.analysemenu.setObjectName(_fromUtf8("analysemenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.newprojectaction = QtGui.QAction(MainWindow)
        self.newprojectaction.setObjectName(_fromUtf8("newprojectaction"))
        self.pauseactionaction = QtGui.QAction(MainWindow)
        self.pauseactionaction.setObjectName(_fromUtf8("pauseactionaction"))
        self.stopprojectaction = QtGui.QAction(MainWindow)
        self.stopprojectaction.setObjectName(_fromUtf8("stopprojectaction"))
        self.exitsoftwareaction = QtGui.QAction(MainWindow)
        self.exitsoftwareaction.setObjectName(_fromUtf8("exitsoftwareaction"))
        self.resetargumentaction = QtGui.QAction(MainWindow)
        self.resetargumentaction.setObjectName(_fromUtf8("resetargumentaction"))
        self.helpdocumentaction = QtGui.QAction(MainWindow)
        self.helpdocumentaction.setObjectName(_fromUtf8("helpdocumentaction"))
        self.aboutsoftwareaction = QtGui.QAction(MainWindow)
        self.aboutsoftwareaction.setObjectName(_fromUtf8("aboutsoftwareaction"))
        self.action_11 = QtGui.QAction(MainWindow)
        self.action_11.setObjectName(_fromUtf8("action_11"))
        self.statisticsaction_1 = QtGui.QAction(MainWindow)
        self.statisticsaction_1.setObjectName(_fromUtf8("statisticsaction_1"))
        self.exportaction_2 = QtGui.QAction(MainWindow)
        self.exportaction_2.setObjectName(_fromUtf8("exportaction_2"))
        self.exportaction_3 = QtGui.QAction(MainWindow)
        self.exportaction_3.setObjectName(_fromUtf8("exportaction_3"))
        self.statisticsaction_2 = QtGui.QAction(MainWindow)
        self.statisticsaction_2.setObjectName(_fromUtf8("statisticsaction_2"))
        self.exportaction_4 = QtGui.QAction(MainWindow)
        self.exportaction_4.setObjectName(_fromUtf8("exportaction_4"))
        self.exportresultaction = QtGui.QAction(MainWindow)
        self.exportresultaction.setObjectName(_fromUtf8("exportresultaction"))
        self.filemenu.addAction(self.newprojectaction)
        self.filemenu.addAction(self.pauseactionaction)
        self.filemenu.addAction(self.stopprojectaction)
        self.filemenu.addSeparator()
        self.filemenu.addAction(self.exitsoftwareaction)
        self.optionmenu.addAction(self.resetargumentaction)
        self.optionmenu.addAction(self.exportresultaction)
        self.helpmenu.addAction(self.helpdocumentaction)
        self.helpmenu.addSeparator()
        self.helpmenu.addAction(self.aboutsoftwareaction)
        self.analysemenu.addAction(self.statisticsaction_1)
        self.analysemenu.addAction(self.exportaction_2)
        self.analysemenu.addAction(self.exportaction_3)
        self.analysemenu.addSeparator()
        self.analysemenu.addAction(self.statisticsaction_2)
        self.analysemenu.addAction(self.exportaction_4)
        self.menubar.addAction(self.filemenu.menuAction())
        self.menubar.addAction(self.optionmenu.menuAction())
        self.menubar.addAction(self.analysemenu.menuAction())
        self.menubar.addAction(self.helpmenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.codingcomboBox.setCurrentIndex(-1)
        self.namingcomboBox.setCurrentIndex(-1)
        self.saveformatcomboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "爬虫软件", None))
        self.urlgroupBox.setTitle(_translate("MainWindow", "起始URL", None))
        self.addurlButton.setText(_translate("MainWindow", "添加", None))
        self.modifyurlButton.setText(_translate("MainWindow", "修改", None))
        self.deleteurlButton.setText(_translate("MainWindow", "删除", None))
        self.emptyurlButton.setText(_translate("MainWindow", "清空", None))
        self.rulegroupBox.setTitle(_translate("MainWindow", "URL获取规则", None))
        self.autoacquireradioButton.setText(_translate("MainWindow", "从页面自动分析获取", None))
        self.matchradioButton.setText(_translate("MainWindow", "域名匹配及指定路径", None))
        self.xpathradioButton.setText(_translate("MainWindow", "Xpath表达式", None))
        self.ruletextlabel.setText(_translate("MainWindow", "匹配规则或\n"
"Xpath表达式", None))
        self.argumentgroupBox.setTitle(_translate("MainWindow", "爬取参数", None))
        self.resolvethreadLabel.setText(_translate("MainWindow", "解析网页线程数：", None))
        self.crawlthreadLabel.setText(_translate("MainWindow", "抓取网页线程数：", None))
        self.requesttimeLabel.setText(_translate("MainWindow", "最长请求时间：", None))
        self.depthLabel.setText(_translate("MainWindow", "爬取深度：", None))
        self.pagenumberLabel.setText(_translate("MainWindow", "最大页面数：", None))
        self.millisecondLabel.setText(_translate("MainWindow", "毫秒", None))
        self.depthexplainlabel.setText(_translate("MainWindow", "(0为不限深度)", None))
        self.pagenumberexplainlabel.setText(_translate("MainWindow", "(0为不限页面数)", None))
        self.savegroupBox.setTitle(_translate("MainWindow", "保存选项", None))
        self.codingcomboBox.setItemText(0, _translate("MainWindow", "UTF-8", None))
        self.codingcomboBox.setItemText(1, _translate("MainWindow", "GB2312", None))
        self.savelocationLabel.setText(_translate("MainWindow", "文件保存位置：", None))
        self.namingLabel.setText(_translate("MainWindow", "文件命名方式：", None))
        self.saveformatLabel.setText(_translate("MainWindow", "文件保存格式：", None))
        self.downloadnumberLabel.setText(_translate("MainWindow", "最多同时下载数：", None))
        self.namingcomboBox.setItemText(0, _translate("MainWindow", "顺序数字", None))
        self.namingcomboBox.setItemText(1, _translate("MainWindow", "项目+顺序数字", None))
        self.namingcomboBox.setItemText(2, _translate("MainWindow", "下载时间", None))
        self.namingcomboBox.setItemText(3, _translate("MainWindow", "Html:Title", None))
        self.codingLabel.setText(_translate("MainWindow", "编码方式：", None))
        self.savelocationpushButton.setText(_translate("MainWindow", "...", None))
        self.saveformatcomboBox.setItemText(0, _translate("MainWindow", "txt", None))
        self.saveformatcomboBox.setItemText(1, _translate("MainWindow", "html", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingtab), _translate("MainWindow", "设置", None))
        self.resultgroupBox.setTitle(_translate("MainWindow", "运行结果", None))
        item = self.resulttableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号", None))
        item = self.resulttableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "文件", None))
        item = self.resulttableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "类型", None))
        item = self.resulttableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "大小", None))
        item = self.resulttableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "状态", None))
        item = self.resulttableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "URL", None))
        self.conditiongroupBox.setTitle(_translate("MainWindow", "运行情况", None))
        self.statusLabel.setText(_translate("MainWindow", "运行状态：", None))
        self.statusdisplayLabel.setText(_translate("MainWindow", "未开始", None))
        self.succeedednumberLabel.setText(_translate("MainWindow", "成功下载网页数：", None))
        self.succeedednumberdisplayLabel.setText(_translate("MainWindow", "0", None))
        self.downloadsizeLabel.setText(_translate("MainWindow", "共下载网页(MB)：", None))
        self.downloadsizedisplayLabel.setText(_translate("MainWindow", "0", None))
        self.runtimeLabel.setText(_translate("MainWindow", "已运行时间：", None))
        self.runtimedisplayLabel.setText(_translate("MainWindow", "00:00:00", None))
        self.failednumberLabel_.setText(_translate("MainWindow", "失败下载网页数：", None))
        self.failednumberdisplayLabel.setText(_translate("MainWindow", "0", None))
        self.downloadspeedLabel.setText(_translate("MainWindow", "平均下载速度(KB/s)：", None))
        self.downloadspeeddisplayLabel.setText(_translate("MainWindow", "0", None))
        self.crawlednumberLabel.setText(_translate("MainWindow", "已爬取网页数：", None))
        self.crawlednumberdisplayLabel.setText(_translate("MainWindow", "0", None))
        self.errornumberLabel.setText(_translate("MainWindow", "错误数：", None))
        self.errornumberdisplayLabel.setText(_translate("MainWindow", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.displaytab), _translate("MainWindow", "显示", None))
        self.nametitleLabel.setText(_translate("MainWindow", "项目名称：", None))
        self.projectnameLabel.setText(_translate("MainWindow", "（未创建）", None))
        self.startButton.setText(_translate("MainWindow", "开始", None))
        self.pauseButton.setText(_translate("MainWindow", "暂停", None))
        self.stopButton.setText(_translate("MainWindow", "停止", None))
        self.filemenu.setTitle(_translate("MainWindow", "文件", None))
        self.optionmenu.setTitle(_translate("MainWindow", "选项", None))
        self.helpmenu.setTitle(_translate("MainWindow", "帮助", None))
        self.analysemenu.setTitle(_translate("MainWindow", "分析", None))
        self.newprojectaction.setText(_translate("MainWindow", "新建项目", None))
        self.pauseactionaction.setText(_translate("MainWindow", "暂停项目", None))
        self.stopprojectaction.setText(_translate("MainWindow", "停止项目", None))
        self.exitsoftwareaction.setText(_translate("MainWindow", "退出软件", None))
        self.resetargumentaction.setText(_translate("MainWindow", "重置参数", None))
        self.helpdocumentaction.setText(_translate("MainWindow", "帮助文档", None))
        self.aboutsoftwareaction.setText(_translate("MainWindow", "关于软件", None))
        self.action_11.setText(_translate("MainWindow", "统计域名网站信息", None))
        self.statisticsaction_1.setText(_translate("MainWindow", "统计单域名网站内信息", None))
        self.exportaction_2.setText(_translate("MainWindow", "导出站内页面互链矩阵", None))
        self.exportaction_3.setText(_translate("MainWindow", "导出对外链接统计信息", None))
        self.statisticsaction_2.setText(_translate("MainWindow", "统计站点间互链信息", None))
        self.exportaction_4.setText(_translate("MainWindow", "导出站点间互链矩阵", None))
        self.exportresultaction.setText(_translate("MainWindow", "导出运行结果", None))

