# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Thu Mar 19 01:22:08 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(985, 656)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.centralLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.centralLayout.setSpacing(20)
        self.centralLayout.setContentsMargins(20, -1, 20, -1)
        self.centralLayout.setObjectName(_fromUtf8("centralLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.settingtab = QtGui.QWidget()
        self.settingtab.setObjectName(_fromUtf8("settingtab"))
        self.settingLayout = QtGui.QVBoxLayout(self.settingtab)
        self.settingLayout.setSpacing(15)
        self.settingLayout.setContentsMargins(18, 13, 18, 21)
        self.settingLayout.setObjectName(_fromUtf8("settingLayout"))
        self.urlgroupBox = QtGui.QGroupBox(self.settingtab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.urlgroupBox.setFont(font)
        self.urlgroupBox.setObjectName(_fromUtf8("urlgroupBox"))
        self.urlgroupLayout = QtGui.QHBoxLayout(self.urlgroupBox)
        self.urlgroupLayout.setSpacing(16)
        self.urlgroupLayout.setContentsMargins(20, -1, 8, -1)
        self.urlgroupLayout.setObjectName(_fromUtf8("urlgroupLayout"))
        self.urltextBrowser = QtGui.QTextBrowser(self.urlgroupBox)
        self.urltextBrowser.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.urltextBrowser.setObjectName(_fromUtf8("urltextBrowser"))
        self.urlgroupLayout.addWidget(self.urltextBrowser)
        self.urlbuttonLayout = QtGui.QVBoxLayout()
        self.urlbuttonLayout.setSpacing(6)
        self.urlbuttonLayout.setObjectName(_fromUtf8("urlbuttonLayout"))
        self.addurlButton = QtGui.QPushButton(self.urlgroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addurlButton.sizePolicy().hasHeightForWidth())
        self.addurlButton.setSizePolicy(sizePolicy)
        self.addurlButton.setMaximumSize(QtCore.QSize(71, 21))
        self.addurlButton.setObjectName(_fromUtf8("addurlButton"))
        self.urlbuttonLayout.addWidget(self.addurlButton)
        self.emptyurlButton = QtGui.QPushButton(self.urlgroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emptyurlButton.sizePolicy().hasHeightForWidth())
        self.emptyurlButton.setSizePolicy(sizePolicy)
        self.emptyurlButton.setMaximumSize(QtCore.QSize(71, 21))
        self.emptyurlButton.setObjectName(_fromUtf8("emptyurlButton"))
        self.urlbuttonLayout.addWidget(self.emptyurlButton)
        self.urlgroupLayout.addLayout(self.urlbuttonLayout)
        self.urlgroupLayout.setStretch(0, 98)
        self.urlgroupLayout.setStretch(1, 11)
        self.settingLayout.addWidget(self.urlgroupBox)
        self.rangegroupBox = QtGui.QGroupBox(self.settingtab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rangegroupBox.setFont(font)
        self.rangegroupBox.setObjectName(_fromUtf8("rangegroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.rangegroupBox)
        self.horizontalLayout.setSpacing(14)
        self.horizontalLayout.setContentsMargins(28, -1, 12, 9)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rangelabel = QtGui.QLabel(self.rangegroupBox)
        self.rangelabel.setObjectName(_fromUtf8("rangelabel"))
        self.horizontalLayout.addWidget(self.rangelabel)
        self.rangeplainTextEdit = QtGui.QPlainTextEdit(self.rangegroupBox)
        self.rangeplainTextEdit.setObjectName(_fromUtf8("rangeplainTextEdit"))
        self.horizontalLayout.addWidget(self.rangeplainTextEdit)
        self.rangetextlabel = QtGui.QLabel(self.rangegroupBox)
        self.rangetextlabel.setObjectName(_fromUtf8("rangetextlabel"))
        self.horizontalLayout.addWidget(self.rangetextlabel)
        self.horizontalLayout.setStretch(0, 29)
        self.horizontalLayout.setStretch(1, 132)
        self.horizontalLayout.setStretch(2, 10)
        self.settingLayout.addWidget(self.rangegroupBox)
        self.rulegroupBox = QtGui.QGroupBox(self.settingtab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rulegroupBox.setFont(font)
        self.rulegroupBox.setObjectName(_fromUtf8("rulegroupBox"))
        self.rulegroupLayout = QtGui.QHBoxLayout(self.rulegroupBox)
        self.rulegroupLayout.setSpacing(18)
        self.rulegroupLayout.setContentsMargins(20, -1, 12, -1)
        self.rulegroupLayout.setObjectName(_fromUtf8("rulegroupLayout"))
        self.ruleLayout = QtGui.QVBoxLayout()
        self.ruleLayout.setSpacing(8)
        self.ruleLayout.setObjectName(_fromUtf8("ruleLayout"))
        self.autoacquireradioButton = QtGui.QRadioButton(self.rulegroupBox)
        self.autoacquireradioButton.setObjectName(_fromUtf8("autoacquireradioButton"))
        self.ruleLayout.addWidget(self.autoacquireradioButton)
        self.matchradioButton = QtGui.QRadioButton(self.rulegroupBox)
        self.matchradioButton.setObjectName(_fromUtf8("matchradioButton"))
        self.ruleLayout.addWidget(self.matchradioButton)
        self.xpathradioButton = QtGui.QRadioButton(self.rulegroupBox)
        self.xpathradioButton.setObjectName(_fromUtf8("xpathradioButton"))
        self.ruleLayout.addWidget(self.xpathradioButton)
        self.rulegroupLayout.addLayout(self.ruleLayout)
        self.ruleplainTextEdit = QtGui.QPlainTextEdit(self.rulegroupBox)
        self.ruleplainTextEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.ruleplainTextEdit.setObjectName(_fromUtf8("ruleplainTextEdit"))
        self.rulegroupLayout.addWidget(self.ruleplainTextEdit)
        self.ruletextlabel = QtGui.QLabel(self.rulegroupBox)
        self.ruletextlabel.setObjectName(_fromUtf8("ruletextlabel"))
        self.rulegroupLayout.addWidget(self.ruletextlabel)
        self.rulegroupLayout.setStretch(0, 25)
        self.rulegroupLayout.setStretch(1, 130)
        self.rulegroupLayout.setStretch(2, 10)
        self.settingLayout.addWidget(self.rulegroupBox)
        self.argumentandsaveLayout = QtGui.QHBoxLayout()
        self.argumentandsaveLayout.setSpacing(28)
        self.argumentandsaveLayout.setObjectName(_fromUtf8("argumentandsaveLayout"))
        self.argumentgroupBox = QtGui.QGroupBox(self.settingtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.argumentgroupBox.sizePolicy().hasHeightForWidth())
        self.argumentgroupBox.setSizePolicy(sizePolicy)
        self.argumentgroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.argumentgroupBox.setFont(font)
        self.argumentgroupBox.setObjectName(_fromUtf8("argumentgroupBox"))
        self.argumentgroupLayout = QtGui.QGridLayout(self.argumentgroupBox)
        self.argumentgroupLayout.setContentsMargins(20, -1, -1, -1)
        self.argumentgroupLayout.setObjectName(_fromUtf8("argumentgroupLayout"))
        self.requesttimeLabel = QtGui.QLabel(self.argumentgroupBox)
        self.requesttimeLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.requesttimeLabel.setObjectName(_fromUtf8("requesttimeLabel"))
        self.argumentgroupLayout.addWidget(self.requesttimeLabel, 7, 0, 1, 1)
        self.depthLabel = QtGui.QLabel(self.argumentgroupBox)
        self.depthLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.depthLabel.setObjectName(_fromUtf8("depthLabel"))
        self.argumentgroupLayout.addWidget(self.depthLabel, 5, 0, 1, 1)
        self.pagenumberLabel = QtGui.QLabel(self.argumentgroupBox)
        self.pagenumberLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.pagenumberLabel.setObjectName(_fromUtf8("pagenumberLabel"))
        self.argumentgroupLayout.addWidget(self.pagenumberLabel, 3, 0, 1, 1)
        self.millisecondLabel = QtGui.QLabel(self.argumentgroupBox)
        self.millisecondLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.millisecondLabel.setObjectName(_fromUtf8("millisecondLabel"))
        self.argumentgroupLayout.addWidget(self.millisecondLabel, 7, 2, 1, 1)
        self.depthexplainlabel = QtGui.QLabel(self.argumentgroupBox)
        self.depthexplainlabel.setObjectName(_fromUtf8("depthexplainlabel"))
        self.argumentgroupLayout.addWidget(self.depthexplainlabel, 5, 2, 1, 1)
        self.depthspinBox = QtGui.QSpinBox(self.argumentgroupBox)
        self.depthspinBox.setEnabled(True)
        self.depthspinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.depthspinBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.depthspinBox.setProperty("value", 3)
        self.depthspinBox.setObjectName(_fromUtf8("depthspinBox"))
        self.argumentgroupLayout.addWidget(self.depthspinBox, 5, 1, 1, 1)
        self.pagenumberspinBox = QtGui.QSpinBox(self.argumentgroupBox)
        self.pagenumberspinBox.setEnabled(True)
        self.pagenumberspinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.pagenumberspinBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pagenumberspinBox.setMaximum(100000)
        self.pagenumberspinBox.setProperty("value", 1000)
        self.pagenumberspinBox.setObjectName(_fromUtf8("pagenumberspinBox"))
        self.argumentgroupLayout.addWidget(self.pagenumberspinBox, 3, 1, 1, 1)
        self.pagenumberexplainlabel = QtGui.QLabel(self.argumentgroupBox)
        self.pagenumberexplainlabel.setObjectName(_fromUtf8("pagenumberexplainlabel"))
        self.argumentgroupLayout.addWidget(self.pagenumberexplainlabel, 3, 2, 1, 1)
        self.requesttimespinBox = QtGui.QSpinBox(self.argumentgroupBox)
        self.requesttimespinBox.setEnabled(True)
        self.requesttimespinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.requesttimespinBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.requesttimespinBox.setMinimum(5)
        self.requesttimespinBox.setMaximum(86400)
        self.requesttimespinBox.setProperty("value", 180)
        self.requesttimespinBox.setObjectName(_fromUtf8("requesttimespinBox"))
        self.argumentgroupLayout.addWidget(self.requesttimespinBox, 7, 1, 1, 1)
        self.itemnumberspinBox = QtGui.QSpinBox(self.argumentgroupBox)
        self.itemnumberspinBox.setEnabled(True)
        self.itemnumberspinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.itemnumberspinBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.itemnumberspinBox.setMaximum(100000)
        self.itemnumberspinBox.setProperty("value", 1000)
        self.itemnumberspinBox.setObjectName(_fromUtf8("itemnumberspinBox"))
        self.argumentgroupLayout.addWidget(self.itemnumberspinBox, 4, 1, 1, 1)
        self.itemnumberexplainlabel = QtGui.QLabel(self.argumentgroupBox)
        self.itemnumberexplainlabel.setObjectName(_fromUtf8("itemnumberexplainlabel"))
        self.argumentgroupLayout.addWidget(self.itemnumberexplainlabel, 4, 2, 1, 1)
        self.itemnumberLabel = QtGui.QLabel(self.argumentgroupBox)
        self.itemnumberLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.itemnumberLabel.setObjectName(_fromUtf8("itemnumberLabel"))
        self.argumentgroupLayout.addWidget(self.itemnumberLabel, 4, 0, 1, 1)
        self.argumentandsaveLayout.addWidget(self.argumentgroupBox)
        self.savegroupBox = QtGui.QGroupBox(self.settingtab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.savegroupBox.setFont(font)
        self.savegroupBox.setObjectName(_fromUtf8("savegroupBox"))
        self.savegroupLayout = QtGui.QGridLayout(self.savegroupBox)
        self.savegroupLayout.setContentsMargins(20, -1, -1, -1)
        self.savegroupLayout.setObjectName(_fromUtf8("savegroupLayout"))
        self.savelocationLabel = QtGui.QLabel(self.savegroupBox)
        self.savelocationLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.savelocationLabel.setObjectName(_fromUtf8("savelocationLabel"))
        self.savegroupLayout.addWidget(self.savelocationLabel, 3, 0, 1, 1)
        self.namingLabel = QtGui.QLabel(self.savegroupBox)
        self.namingLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.namingLabel.setObjectName(_fromUtf8("namingLabel"))
        self.savegroupLayout.addWidget(self.namingLabel, 6, 0, 1, 1)
        self.saveformatLabel = QtGui.QLabel(self.savegroupBox)
        self.saveformatLabel.setMaximumSize(QtCore.QSize(104, 16777215))
        self.saveformatLabel.setObjectName(_fromUtf8("saveformatLabel"))
        self.savegroupLayout.addWidget(self.saveformatLabel, 5, 0, 1, 1)
        self.namingcomboBox = QtGui.QComboBox(self.savegroupBox)
        self.namingcomboBox.setMaximumSize(QtCore.QSize(151, 16777215))
        self.namingcomboBox.setObjectName(_fromUtf8("namingcomboBox"))
        self.namingcomboBox.addItem(_fromUtf8(""))
        self.namingcomboBox.addItem(_fromUtf8(""))
        self.namingcomboBox.addItem(_fromUtf8(""))
        self.savegroupLayout.addWidget(self.namingcomboBox, 6, 1, 1, 1)
        self.savelocationpushButton = QtGui.QPushButton(self.savegroupBox)
        self.savelocationpushButton.setMinimumSize(QtCore.QSize(28, 20))
        self.savelocationpushButton.setMaximumSize(QtCore.QSize(28, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.savelocationpushButton.setFont(font)
        self.savelocationpushButton.setObjectName(_fromUtf8("savelocationpushButton"))
        self.savegroupLayout.addWidget(self.savelocationpushButton, 3, 2, 1, 1)
        self.saveformatcomboBox = QtGui.QComboBox(self.savegroupBox)
        self.saveformatcomboBox.setMaximumSize(QtCore.QSize(151, 16777215))
        self.saveformatcomboBox.setObjectName(_fromUtf8("saveformatcomboBox"))
        self.saveformatcomboBox.addItem(_fromUtf8(""))
        self.saveformatcomboBox.addItem(_fromUtf8(""))
        self.savegroupLayout.addWidget(self.saveformatcomboBox, 5, 1, 1, 1)
        self.savelocationlineEdit = QtGui.QLineEdit(self.savegroupBox)
        self.savelocationlineEdit.setMinimumSize(QtCore.QSize(319, 0))
        self.savelocationlineEdit.setMaximumSize(QtCore.QSize(400, 16777215))
        self.savelocationlineEdit.setReadOnly(True)
        self.savelocationlineEdit.setObjectName(_fromUtf8("savelocationlineEdit"))
        self.savegroupLayout.addWidget(self.savelocationlineEdit, 3, 1, 1, 1)
        self.savelocationspaceLabel = QtGui.QLabel(self.savegroupBox)
        self.savelocationspaceLabel.setText(_fromUtf8(""))
        self.savelocationspaceLabel.setObjectName(_fromUtf8("savelocationspaceLabel"))
        self.savegroupLayout.addWidget(self.savelocationspaceLabel, 3, 3, 1, 1)
        self.argumentandsaveLayout.addWidget(self.savegroupBox)
        self.argumentandsaveLayout.setStretch(0, 30)
        self.argumentandsaveLayout.setStretch(1, 50)
        self.settingLayout.addLayout(self.argumentandsaveLayout)
        self.settingLayout.setStretch(0, 38)
        self.settingLayout.setStretch(1, 25)
        self.settingLayout.setStretch(2, 35)
        self.settingLayout.setStretch(3, 38)
        self.tabWidget.addTab(self.settingtab, _fromUtf8(""))
        self.displaytab = QtGui.QWidget()
        self.displaytab.setObjectName(_fromUtf8("displaytab"))
        self.displayLayout = QtGui.QVBoxLayout(self.displaytab)
        self.displayLayout.setSpacing(15)
        self.displayLayout.setContentsMargins(18, 13, 18, 21)
        self.displayLayout.setObjectName(_fromUtf8("displayLayout"))
        self.resultgroupBox = QtGui.QGroupBox(self.displaytab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resultgroupBox.setFont(font)
        self.resultgroupBox.setObjectName(_fromUtf8("resultgroupBox"))
        self.resultgroupLayout = QtGui.QVBoxLayout(self.resultgroupBox)
        self.resultgroupLayout.setContentsMargins(20, -1, 20, 15)
        self.resultgroupLayout.setObjectName(_fromUtf8("resultgroupLayout"))
        self.resultplainTextEdit = QtGui.QPlainTextEdit(self.resultgroupBox)
        self.resultplainTextEdit.setAutoFillBackground(True)
        self.resultplainTextEdit.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.resultplainTextEdit.setReadOnly(True)
        self.resultplainTextEdit.setBackgroundVisible(False)
        self.resultplainTextEdit.setObjectName(_fromUtf8("resultplainTextEdit"))
        self.resultgroupLayout.addWidget(self.resultplainTextEdit)
        self.displayLayout.addWidget(self.resultgroupBox)
        self.conditiongroupBox = QtGui.QGroupBox(self.displaytab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.conditiongroupBox.setFont(font)
        self.conditiongroupBox.setObjectName(_fromUtf8("conditiongroupBox"))
        self.conditiongroupLayout = QtGui.QVBoxLayout(self.conditiongroupBox)
        self.conditiongroupLayout.setContentsMargins(30, 8, 9, 15)
        self.conditiongroupLayout.setObjectName(_fromUtf8("conditiongroupLayout"))
        self.conditiongridLayout = QtGui.QGridLayout()
        self.conditiongridLayout.setObjectName(_fromUtf8("conditiongridLayout"))
        self.label1 = QtGui.QLabel(self.conditiongroupBox)
        self.label1.setMaximumSize(QtCore.QSize(123, 16777215))
        self.label1.setObjectName(_fromUtf8("label1"))
        self.conditiongridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.statusLabel = QtGui.QLabel(self.conditiongroupBox)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.conditiongridLayout.addWidget(self.statusLabel, 0, 1, 1, 1)
        self.responsecountLabel = QtGui.QLabel(self.conditiongroupBox)
        self.responsecountLabel.setObjectName(_fromUtf8("responsecountLabel"))
        self.conditiongridLayout.addWidget(self.responsecountLabel, 0, 3, 1, 1)
        self.label7 = QtGui.QLabel(self.conditiongroupBox)
        self.label7.setMaximumSize(QtCore.QSize(133, 16777215))
        self.label7.setObjectName(_fromUtf8("label7"))
        self.conditiongridLayout.addWidget(self.label7, 0, 4, 1, 1)
        self.itemscrapedLabel = QtGui.QLabel(self.conditiongroupBox)
        self.itemscrapedLabel.setObjectName(_fromUtf8("itemscrapedLabel"))
        self.conditiongridLayout.addWidget(self.itemscrapedLabel, 0, 5, 1, 1)
        self.label2 = QtGui.QLabel(self.conditiongroupBox)
        self.label2.setMaximumSize(QtCore.QSize(118, 16777215))
        self.label2.setObjectName(_fromUtf8("label2"))
        self.conditiongridLayout.addWidget(self.label2, 1, 0, 1, 1)
        self.runtimeLabel = QtGui.QLabel(self.conditiongroupBox)
        self.runtimeLabel.setObjectName(_fromUtf8("runtimeLabel"))
        self.conditiongridLayout.addWidget(self.runtimeLabel, 1, 1, 1, 1)
        self.label5 = QtGui.QLabel(self.conditiongroupBox)
        self.label5.setMaximumSize(QtCore.QSize(129, 16777215))
        self.label5.setObjectName(_fromUtf8("label5"))
        self.conditiongridLayout.addWidget(self.label5, 1, 2, 1, 1)
        self.responsebytesLabel = QtGui.QLabel(self.conditiongroupBox)
        self.responsebytesLabel.setObjectName(_fromUtf8("responsebytesLabel"))
        self.conditiongridLayout.addWidget(self.responsebytesLabel, 1, 3, 1, 1)
        self.label8 = QtGui.QLabel(self.conditiongroupBox)
        self.label8.setMaximumSize(QtCore.QSize(133, 16777215))
        self.label8.setObjectName(_fromUtf8("label8"))
        self.conditiongridLayout.addWidget(self.label8, 1, 4, 1, 1)
        self.itemdownloadLabel = QtGui.QLabel(self.conditiongroupBox)
        self.itemdownloadLabel.setObjectName(_fromUtf8("itemdownloadLabel"))
        self.conditiongridLayout.addWidget(self.itemdownloadLabel, 1, 5, 1, 1)
        self.label3 = QtGui.QLabel(self.conditiongroupBox)
        self.label3.setMaximumSize(QtCore.QSize(118, 16777215))
        self.label3.setObjectName(_fromUtf8("label3"))
        self.conditiongridLayout.addWidget(self.label3, 2, 0, 1, 1)
        self.requestcountLabel = QtGui.QLabel(self.conditiongroupBox)
        self.requestcountLabel.setObjectName(_fromUtf8("requestcountLabel"))
        self.conditiongridLayout.addWidget(self.requestcountLabel, 2, 1, 1, 1)
        self.label6 = QtGui.QLabel(self.conditiongroupBox)
        self.label6.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label6.setObjectName(_fromUtf8("label6"))
        self.conditiongridLayout.addWidget(self.label6, 2, 2, 1, 1)
        self.response200countLabel = QtGui.QLabel(self.conditiongroupBox)
        self.response200countLabel.setObjectName(_fromUtf8("response200countLabel"))
        self.conditiongridLayout.addWidget(self.response200countLabel, 2, 3, 1, 1)
        self.label4 = QtGui.QLabel(self.conditiongroupBox)
        self.label4.setMaximumSize(QtCore.QSize(129, 16777215))
        self.label4.setObjectName(_fromUtf8("label4"))
        self.conditiongridLayout.addWidget(self.label4, 0, 2, 1, 1)
        self.conditiongroupLayout.addLayout(self.conditiongridLayout)
        self.displayLayout.addWidget(self.conditiongroupBox)
        self.displayLayout.setStretch(0, 13)
        self.displayLayout.setStretch(1, 6)
        self.tabWidget.addTab(self.displaytab, _fromUtf8(""))
        self.centralLayout.addWidget(self.tabWidget)
        self.nameandcontrolhorizontalLayout = QtGui.QHBoxLayout()
        self.nameandcontrolhorizontalLayout.setSpacing(0)
        self.nameandcontrolhorizontalLayout.setContentsMargins(20, -1, 10, -1)
        self.nameandcontrolhorizontalLayout.setObjectName(_fromUtf8("nameandcontrolhorizontalLayout"))
        self.nameLayout = QtGui.QHBoxLayout()
        self.nameLayout.setSpacing(0)
        self.nameLayout.setContentsMargins(-1, 0, -1, -1)
        self.nameLayout.setObjectName(_fromUtf8("nameLayout"))
        self.nametitleLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nametitleLabel.setFont(font)
        self.nametitleLabel.setObjectName(_fromUtf8("nametitleLabel"))
        self.nameLayout.addWidget(self.nametitleLabel)
        self.projectnameLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.projectnameLabel.setFont(font)
        self.projectnameLabel.setObjectName(_fromUtf8("projectnameLabel"))
        self.nameLayout.addWidget(self.projectnameLabel)
        self.nameandcontrolhorizontalLayout.addLayout(self.nameLayout)
        self.controlLayout = QtGui.QHBoxLayout()
        self.controlLayout.setSpacing(20)
        self.controlLayout.setObjectName(_fromUtf8("controlLayout"))
        spacerItem = QtGui.QSpacerItem(602, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.controlLayout.addItem(spacerItem)
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setIconSize(QtCore.QSize(16, 16))
        self.startButton.setAutoRepeatDelay(300)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.controlLayout.addWidget(self.startButton)
        self.pauseButton = QtGui.QPushButton(self.centralwidget)
        self.pauseButton.setObjectName(_fromUtf8("pauseButton"))
        self.controlLayout.addWidget(self.pauseButton)
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.controlLayout.addWidget(self.stopButton)
        self.nameandcontrolhorizontalLayout.addLayout(self.controlLayout)
        self.centralLayout.addLayout(self.nameandcontrolhorizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 985, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.filemenu = QtGui.QMenu(self.menubar)
        self.filemenu.setObjectName(_fromUtf8("filemenu"))
        self.helpmenu = QtGui.QMenu(self.menubar)
        self.helpmenu.setObjectName(_fromUtf8("helpmenu"))
        self.analyse1menu = QtGui.QMenu(self.menubar)
        self.analyse1menu.setObjectName(_fromUtf8("analyse1menu"))
        self.menu_1 = QtGui.QMenu(self.analyse1menu)
        self.menu_1.setObjectName(_fromUtf8("menu_1"))
        self.menu_2 = QtGui.QMenu(self.analyse1menu)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.analyse1menu)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_4 = QtGui.QMenu(self.analyse1menu)
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        self.analyse2menu = QtGui.QMenu(self.menubar)
        self.analyse2menu.setObjectName(_fromUtf8("analyse2menu"))
        self.menu_5 = QtGui.QMenu(self.analyse2menu)
        self.menu_5.setObjectName(_fromUtf8("menu_5"))
        self.menu_6 = QtGui.QMenu(self.analyse2menu)
        self.menu_6.setObjectName(_fromUtf8("menu_6"))
        self.menu_7 = QtGui.QMenu(self.analyse2menu)
        self.menu_7.setObjectName(_fromUtf8("menu_7"))
        self.menu_8 = QtGui.QMenu(self.analyse2menu)
        self.menu_8.setObjectName(_fromUtf8("menu_8"))
        self.outputmenu = QtGui.QMenu(self.menubar)
        self.outputmenu.setObjectName(_fromUtf8("outputmenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.newprojectaction = QtGui.QAction(MainWindow)
        self.newprojectaction.setObjectName(_fromUtf8("newprojectaction"))
        self.pauseactionaction = QtGui.QAction(MainWindow)
        self.pauseactionaction.setObjectName(_fromUtf8("pauseactionaction"))
        self.stopprojectaction = QtGui.QAction(MainWindow)
        self.stopprojectaction.setObjectName(_fromUtf8("stopprojectaction"))
        self.exitsoftwareaction = QtGui.QAction(MainWindow)
        self.exitsoftwareaction.setObjectName(_fromUtf8("exitsoftwareaction"))
        self.resetargumentaction = QtGui.QAction(MainWindow)
        self.resetargumentaction.setObjectName(_fromUtf8("resetargumentaction"))
        self.helpdocumentaction = QtGui.QAction(MainWindow)
        self.helpdocumentaction.setObjectName(_fromUtf8("helpdocumentaction"))
        self.aboutsoftwareaction = QtGui.QAction(MainWindow)
        self.aboutsoftwareaction.setObjectName(_fromUtf8("aboutsoftwareaction"))
        self.action_11 = QtGui.QAction(MainWindow)
        self.action_11.setObjectName(_fromUtf8("action_11"))
        self.buildoutput1action = QtGui.QAction(MainWindow)
        self.buildoutput1action.setObjectName(_fromUtf8("buildoutput1action"))
        self.exportaction_2 = QtGui.QAction(MainWindow)
        self.exportaction_2.setObjectName(_fromUtf8("exportaction_2"))
        self.exportaction_3 = QtGui.QAction(MainWindow)
        self.exportaction_3.setObjectName(_fromUtf8("exportaction_3"))
        self.statisticsaction_2 = QtGui.QAction(MainWindow)
        self.statisticsaction_2.setObjectName(_fromUtf8("statisticsaction_2"))
        self.exportaction_4 = QtGui.QAction(MainWindow)
        self.exportaction_4.setObjectName(_fromUtf8("exportaction_4"))
        self.exportresultaction = QtGui.QAction(MainWindow)
        self.exportresultaction.setObjectName(_fromUtf8("exportresultaction"))
        self.startprojectaction = QtGui.QAction(MainWindow)
        self.startprojectaction.setObjectName(_fromUtf8("startprojectaction"))
        self.action01 = QtGui.QAction(MainWindow)
        self.action01.setObjectName(_fromUtf8("action01"))
        self.action2 = QtGui.QAction(MainWindow)
        self.action2.setObjectName(_fromUtf8("action2"))
        self.action3 = QtGui.QAction(MainWindow)
        self.action3.setObjectName(_fromUtf8("action3"))
        self.action4 = QtGui.QAction(MainWindow)
        self.action4.setObjectName(_fromUtf8("action4"))
        self.action6 = QtGui.QAction(MainWindow)
        self.action6.setObjectName(_fromUtf8("action6"))
        self.action5 = QtGui.QAction(MainWindow)
        self.action5.setObjectName(_fromUtf8("action5"))
        self.action7 = QtGui.QAction(MainWindow)
        self.action7.setObjectName(_fromUtf8("action7"))
        self.action8 = QtGui.QAction(MainWindow)
        self.action8.setObjectName(_fromUtf8("action8"))
        self.action9 = QtGui.QAction(MainWindow)
        self.action9.setObjectName(_fromUtf8("action9"))
        self.action_14 = QtGui.QAction(MainWindow)
        self.action_14.setText(_fromUtf8(""))
        self.action_14.setObjectName(_fromUtf8("action_14"))
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action1_2 = QtGui.QAction(MainWindow)
        self.action1_2.setObjectName(_fromUtf8("action1_2"))
        self.action2_2 = QtGui.QAction(MainWindow)
        self.action2_2.setObjectName(_fromUtf8("action2_2"))
        self.action3_2 = QtGui.QAction(MainWindow)
        self.action3_2.setObjectName(_fromUtf8("action3_2"))
        self.action11 = QtGui.QAction(MainWindow)
        self.action11.setObjectName(_fromUtf8("action11"))
        self.action12 = QtGui.QAction(MainWindow)
        self.action12.setObjectName(_fromUtf8("action12"))
        self.action13 = QtGui.QAction(MainWindow)
        self.action13.setObjectName(_fromUtf8("action13"))
        self.action21 = QtGui.QAction(MainWindow)
        self.action21.setObjectName(_fromUtf8("action21"))
        self.action22 = QtGui.QAction(MainWindow)
        self.action22.setObjectName(_fromUtf8("action22"))
        self.action23 = QtGui.QAction(MainWindow)
        self.action23.setObjectName(_fromUtf8("action23"))
        self.action31 = QtGui.QAction(MainWindow)
        self.action31.setObjectName(_fromUtf8("action31"))
        self.action32 = QtGui.QAction(MainWindow)
        self.action32.setObjectName(_fromUtf8("action32"))
        self.action33 = QtGui.QAction(MainWindow)
        self.action33.setObjectName(_fromUtf8("action33"))
        self.action41 = QtGui.QAction(MainWindow)
        self.action41.setObjectName(_fromUtf8("action41"))
        self.action42 = QtGui.QAction(MainWindow)
        self.action42.setObjectName(_fromUtf8("action42"))
        self.action43 = QtGui.QAction(MainWindow)
        self.action43.setObjectName(_fromUtf8("action43"))
        self.buildoutput2action = QtGui.QAction(MainWindow)
        self.buildoutput2action.setObjectName(_fromUtf8("buildoutput2action"))
        self.action02 = QtGui.QAction(MainWindow)
        self.action02.setObjectName(_fromUtf8("action02"))
        self.action51 = QtGui.QAction(MainWindow)
        self.action51.setObjectName(_fromUtf8("action51"))
        self.action52 = QtGui.QAction(MainWindow)
        self.action52.setObjectName(_fromUtf8("action52"))
        self.action53 = QtGui.QAction(MainWindow)
        self.action53.setObjectName(_fromUtf8("action53"))
        self.action61 = QtGui.QAction(MainWindow)
        self.action61.setObjectName(_fromUtf8("action61"))
        self.action62 = QtGui.QAction(MainWindow)
        self.action62.setObjectName(_fromUtf8("action62"))
        self.action63 = QtGui.QAction(MainWindow)
        self.action63.setObjectName(_fromUtf8("action63"))
        self.action71 = QtGui.QAction(MainWindow)
        self.action71.setObjectName(_fromUtf8("action71"))
        self.action72 = QtGui.QAction(MainWindow)
        self.action72.setObjectName(_fromUtf8("action72"))
        self.action73 = QtGui.QAction(MainWindow)
        self.action73.setObjectName(_fromUtf8("action73"))
        self.action81 = QtGui.QAction(MainWindow)
        self.action81.setObjectName(_fromUtf8("action81"))
        self.action82 = QtGui.QAction(MainWindow)
        self.action82.setObjectName(_fromUtf8("action82"))
        self.action83 = QtGui.QAction(MainWindow)
        self.action83.setObjectName(_fromUtf8("action83"))
        self.outputaction = QtGui.QAction(MainWindow)
        self.outputaction.setObjectName(_fromUtf8("outputaction"))
        self.documentationaction = QtGui.QAction(MainWindow)
        self.documentationaction.setObjectName(_fromUtf8("documentationaction"))
        self.filemenu.addAction(self.newprojectaction)
        self.filemenu.addAction(self.startprojectaction)
        self.filemenu.addAction(self.pauseactionaction)
        self.filemenu.addAction(self.stopprojectaction)
        self.filemenu.addSeparator()
        self.filemenu.addAction(self.exitsoftwareaction)
        self.helpmenu.addAction(self.documentationaction)
        self.helpmenu.addAction(self.helpdocumentaction)
        self.helpmenu.addSeparator()
        self.helpmenu.addAction(self.aboutsoftwareaction)
        self.menu_1.addAction(self.action11)
        self.menu_1.addAction(self.action12)
        self.menu_1.addAction(self.action13)
        self.menu_2.addAction(self.action21)
        self.menu_2.addAction(self.action22)
        self.menu_2.addAction(self.action23)
        self.menu_3.addAction(self.action31)
        self.menu_3.addAction(self.action32)
        self.menu_3.addAction(self.action33)
        self.menu_4.addAction(self.action41)
        self.menu_4.addAction(self.action42)
        self.menu_4.addAction(self.action43)
        self.analyse1menu.addAction(self.action01)
        self.analyse1menu.addAction(self.menu_1.menuAction())
        self.analyse1menu.addAction(self.menu_2.menuAction())
        self.analyse1menu.addAction(self.menu_3.menuAction())
        self.analyse1menu.addAction(self.menu_4.menuAction())
        self.menu_5.addAction(self.action51)
        self.menu_5.addAction(self.action52)
        self.menu_5.addAction(self.action53)
        self.menu_6.addAction(self.action61)
        self.menu_6.addAction(self.action62)
        self.menu_6.addAction(self.action63)
        self.menu_7.addAction(self.action71)
        self.menu_7.addAction(self.action72)
        self.menu_7.addAction(self.action73)
        self.menu_8.addAction(self.action81)
        self.menu_8.addAction(self.action82)
        self.menu_8.addAction(self.action83)
        self.analyse2menu.addAction(self.action02)
        self.analyse2menu.addAction(self.menu_5.menuAction())
        self.analyse2menu.addAction(self.menu_6.menuAction())
        self.analyse2menu.addAction(self.menu_7.menuAction())
        self.analyse2menu.addAction(self.menu_8.menuAction())
        self.outputmenu.addAction(self.outputaction)
        self.menubar.addAction(self.filemenu.menuAction())
        self.menubar.addAction(self.outputmenu.menuAction())
        self.menubar.addAction(self.analyse1menu.menuAction())
        self.menubar.addAction(self.analyse2menu.menuAction())
        self.menubar.addAction(self.helpmenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.namingcomboBox.setCurrentIndex(-1)
        self.saveformatcomboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Luna_spider", None))
        self.urlgroupBox.setTitle(_translate("MainWindow", "起始URL", None))
        self.addurlButton.setText(_translate("MainWindow", "添加", None))
        self.emptyurlButton.setText(_translate("MainWindow", "清空", None))
        self.rangegroupBox.setTitle(_translate("MainWindow", "爬取范围", None))
        self.rangelabel.setText(_translate("MainWindow", "<html><head/><body><p>设置限定域:</p><p>爬取到的url在域内时,</p><p>才对其进行跟踪和下载</p></body></html>", None))
        self.rangeplainTextEdit.setPlainText(_translate("MainWindow", "allowed_domains=(\'example.com\', \'im.nju.edu.cn\')", None))
        self.rangetextlabel.setText(_translate("MainWindow", "按范例将引号\n"
"中内容替换；\n"
"不限定则清空", None))
        self.rulegroupBox.setTitle(_translate("MainWindow", "条目抓取规则", None))
        self.autoacquireradioButton.setText(_translate("MainWindow", "从页面自动抓取", None))
        self.matchradioButton.setText(_translate("MainWindow", "网址匹配及指定路径", None))
        self.xpathradioButton.setText(_translate("MainWindow", "Xpath表达式", None))
        self.ruletextlabel.setText(_translate("MainWindow", "匹配规则或\n"
"Xpath表达式", None))
        self.argumentgroupBox.setTitle(_translate("MainWindow", "爬取参数", None))
        self.requesttimeLabel.setText(_translate("MainWindow", "最长请求时间：", None))
        self.depthLabel.setText(_translate("MainWindow", "爬取深度：", None))
        self.pagenumberLabel.setText(_translate("MainWindow", "最大爬取页面数：", None))
        self.millisecondLabel.setText(_translate("MainWindow", " 秒", None))
        self.depthexplainlabel.setText(_translate("MainWindow", "(0为不限深度)", None))
        self.pagenumberexplainlabel.setText(_translate("MainWindow", "(0为不限页面数)", None))
        self.itemnumberexplainlabel.setText(_translate("MainWindow", "(0为不限条目数)", None))
        self.itemnumberLabel.setText(_translate("MainWindow", "最大抓取条目数：", None))
        self.savegroupBox.setTitle(_translate("MainWindow", "保存选项", None))
        self.savelocationLabel.setText(_translate("MainWindow", "文件保存位置：", None))
        self.namingLabel.setText(_translate("MainWindow", "文件命名方式：", None))
        self.saveformatLabel.setText(_translate("MainWindow", "文件保存格式：", None))
        self.namingcomboBox.setItemText(0, _translate("MainWindow", "顺序数字", None))
        self.namingcomboBox.setItemText(1, _translate("MainWindow", "项目+顺序数字", None))
        self.namingcomboBox.setItemText(2, _translate("MainWindow", "Html:Title", None))
        self.savelocationpushButton.setText(_translate("MainWindow", "...", None))
        self.saveformatcomboBox.setItemText(0, _translate("MainWindow", "txt", None))
        self.saveformatcomboBox.setItemText(1, _translate("MainWindow", "html", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingtab), _translate("MainWindow", "设置", None))
        self.resultgroupBox.setTitle(_translate("MainWindow", "运行情况", None))
        self.conditiongroupBox.setTitle(_translate("MainWindow", "运行结果", None))
        self.label1.setText(_translate("MainWindow", "运行状态：", None))
        self.statusLabel.setText(_translate("MainWindow", "未开始", None))
        self.responsecountLabel.setText(_translate("MainWindow", "0", None))
        self.label7.setText(_translate("MainWindow", "抓取条目数：", None))
        self.itemscrapedLabel.setText(_translate("MainWindow", "0", None))
        self.label2.setText(_translate("MainWindow", "已运行时间：", None))
        self.runtimeLabel.setText(_translate("MainWindow", "00:00:00", None))
        self.label5.setText(_translate("MainWindow", "响应字节数：", None))
        self.responsebytesLabel.setText(_translate("MainWindow", "0", None))
        self.label8.setText(_translate("MainWindow", "成功下载条目数：", None))
        self.itemdownloadLabel.setText(_translate("MainWindow", "0", None))
        self.label3.setText(_translate("MainWindow", "请求页面数：", None))
        self.requestcountLabel.setText(_translate("MainWindow", "0", None))
        self.label6.setText(_translate("MainWindow", "响应成功页面数(200)：", None))
        self.response200countLabel.setText(_translate("MainWindow", "0", None))
        self.label4.setText(_translate("MainWindow", "响应页面数：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.displaytab), _translate("MainWindow", "显示", None))
        self.nametitleLabel.setText(_translate("MainWindow", "项目名称：", None))
        self.projectnameLabel.setText(_translate("MainWindow", "（未创建）", None))
        self.startButton.setText(_translate("MainWindow", "开始", None))
        self.pauseButton.setText(_translate("MainWindow", "暂停", None))
        self.stopButton.setText(_translate("MainWindow", "停止", None))
        self.filemenu.setTitle(_translate("MainWindow", "文件", None))
        self.helpmenu.setTitle(_translate("MainWindow", "帮助", None))
        self.analyse1menu.setTitle(_translate("MainWindow", "基于抓取条目的分析", None))
        self.menu_1.setTitle(_translate("MainWindow", "基于抓取条目的链接列表", None))
        self.menu_2.setTitle(_translate("MainWindow", "基于起始url对应站点的链接统计", None))
        self.menu_3.setTitle(_translate("MainWindow", "基于限定域的链接统计", None))
        self.menu_4.setTitle(_translate("MainWindow", "基于抓取页面的链接统计", None))
        self.analyse2menu.setTitle(_translate("MainWindow", "基于爬取页面的分析", None))
        self.menu_5.setTitle(_translate("MainWindow", "基于爬取条目的链接列表", None))
        self.menu_6.setTitle(_translate("MainWindow", "基于起始url对应站点的链接统计", None))
        self.menu_7.setTitle(_translate("MainWindow", "基于限定域的链接统计", None))
        self.menu_8.setTitle(_translate("MainWindow", "基于爬取页面的链接统计", None))
        self.outputmenu.setTitle(_translate("MainWindow", "分析", None))
        self.newprojectaction.setText(_translate("MainWindow", "新建项目", None))
        self.pauseactionaction.setText(_translate("MainWindow", "暂停/继续项目", None))
        self.stopprojectaction.setText(_translate("MainWindow", "停止项目", None))
        self.exitsoftwareaction.setText(_translate("MainWindow", "退出软件", None))
        self.resetargumentaction.setText(_translate("MainWindow", "重置参数", None))
        self.helpdocumentaction.setText(_translate("MainWindow", "帮助文档", None))
        self.aboutsoftwareaction.setText(_translate("MainWindow", "关于软件", None))
        self.action_11.setText(_translate("MainWindow", "统计域名网站信息", None))
        self.buildoutput1action.setText(_translate("MainWindow", "生成统计结果", None))
        self.exportaction_2.setText(_translate("MainWindow", "导出站内页面互链矩阵", None))
        self.exportaction_3.setText(_translate("MainWindow", "导出对外链接统计信息", None))
        self.statisticsaction_2.setText(_translate("MainWindow", "统计站点间互链信息", None))
        self.exportaction_4.setText(_translate("MainWindow", "导出站点间互链矩阵", None))
        self.exportresultaction.setText(_translate("MainWindow", "导出运行结果", None))
        self.startprojectaction.setText(_translate("MainWindow", "开始项目", None))
        self.action01.setText(_translate("MainWindow", "运行结果", None))
        self.action2.setText(_translate("MainWindow", "各页面链接", None))
        self.action3.setText(_translate("MainWindow", "各页面抓取范围内链接", None))
        self.action4.setText(_translate("MainWindow", "各页面抓取范围外链接", None))
        self.action6.setText(_translate("MainWindow", "站点间链接统计", None))
        self.action5.setText(_translate("MainWindow", "站点的各类链接统计", None))
        self.action7.setText(_translate("MainWindow", "站点间链接统计矩阵", None))
        self.action8.setText(_translate("MainWindow", "页面的各类链接统计", None))
        self.action9.setText(_translate("MainWindow", "页面间链接统计矩阵", None))
        self.action_4.setText(_translate("MainWindow", "各条目链接", None))
        self.action1_2.setText(_translate("MainWindow", "1", None))
        self.action2_2.setText(_translate("MainWindow", "2", None))
        self.action3_2.setText(_translate("MainWindow", "3", None))
        self.action11.setText(_translate("MainWindow", "所有链接的列表", None))
        self.action12.setText(_translate("MainWindow", "抓取范围内链接列表", None))
        self.action13.setText(_translate("MainWindow", "抓取范围外链接列表", None))
        self.action21.setText(_translate("MainWindow", "各类链接统计", None))
        self.action22.setText(_translate("MainWindow", "互链统计", None))
        self.action23.setText(_translate("MainWindow", "互链统计矩阵", None))
        self.action31.setText(_translate("MainWindow", "各类链接统计", None))
        self.action32.setText(_translate("MainWindow", "互链统计", None))
        self.action33.setText(_translate("MainWindow", "互链统计矩阵", None))
        self.action41.setText(_translate("MainWindow", "各类链接统计", None))
        self.action42.setText(_translate("MainWindow", "互链统计矩阵", None))
        self.action43.setText(_translate("MainWindow", "互链统计矩阵(去除全零行)", None))
        self.buildoutput2action.setText(_translate("MainWindow", "生成统计结果", None))
        self.action02.setText(_translate("MainWindow", "运行结果", None))
        self.action51.setText(_translate("MainWindow", "所有链接的列表", None))
        self.action52.setText(_translate("MainWindow", "爬取范围内链接列表", None))
        self.action53.setText(_translate("MainWindow", "爬取范围外链接列表", None))
        self.action61.setText(_translate("MainWindow", "各类链接统计", None))
        self.action62.setText(_translate("MainWindow", "互链统计", None))
        self.action63.setText(_translate("MainWindow", "互链统计矩阵", None))
        self.action71.setText(_translate("MainWindow", "各类链接统计", None))
        self.action72.setText(_translate("MainWindow", "互链统计", None))
        self.action73.setText(_translate("MainWindow", "互链统计矩阵", None))
        self.action81.setText(_translate("MainWindow", "各类链接统计", None))
        self.action82.setText(_translate("MainWindow", "互链统计矩阵", None))
        self.action83.setText(_translate("MainWindow", "互链统计矩阵(去除全零行)", None))
        self.outputaction.setText(_translate("MainWindow", "生成统计结果", None))
        self.documentationaction.setText(_translate("MainWindow", "说明文档", None))

